baseURL = 'https://dipankarmazumdar.github.io/'
languageCode = 'en-us'
title = 'Dipankar Mazumdar | Data Systems Architecture'
theme = "terminal"

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showFullContent = false
  readingTime = false
  # Avatar settings
  avatar = "avatar.jpg"
  portrait = "avatar.jpg"

  [params.terminal]
    prefix = "dipankar@lakehouse:~$ "

  [params.logo]
    logoText = "DM"
    logoHomeLink = "/"

# Navbar Configuration
[[menu.main]]
  name = "About"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Writing"
  url = "/writing"
  weight = 2

[[menu.main]]
  name = "Research"
  url = "/research"
  weight = 3

[[menu.main]]
  name = "Speaking"
  url = "/speaking"
  weight = 4