baseURL = 'https://dipankarmazumdar.github.io/'
languageCode = 'en-us'
title = 'Dipankar Mazumdar'
theme = "terminal"

[params]
  # This is the "kill switch" for those [] symbols on the home page
  fullWidthTheme = true
  maxWidth = "95%"
  hideLatestPosts = true
  contentTypeName = "posts"
  themeColor = "orange"
  avatar = "avatar.jpg"

  [params.terminal]
    prefix = "dipankar@lakehouse:~$ "

  [params.logo]
    logoText = "DM"
    logoHomeLink = "/"

[[menu.main]]
  name = "About"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Writing"
  url = "/writing/"
  weight = 2

[[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 3

[[menu.main]]
  name = "Speaking"
  url = "/speaking/"
  weight = 4

[[menu.main]]
  name = "Books"
  url = "/books/"
  weight = 5